

obj-y = test.o cache-probe.o

# test framework
obj-y += fw.o

#obj-y += performance.o usermap.o

# test contain some command
obj-y += memory.o

obj-y += smp-test/
obj-y += other-test/
obj-y += fw-test/
