

SRCS = old_test.c test.c performance.c cache-probe.c usermap.c

SRCS += memory.c

# This order is important
SRCS += tst_smp_ipi.c
SRCS += tst_pcpu.c
SRCS += tst_smp_msg0.c
SRCS += tst_smp_msg1.c

SRCS += tst_llsc.c
SRCS += tst_atomic0.c
SRCS += tst_atomic1.c
SRCS += tst_atomic2.c
SRCS += tst_atomic3.c
SRCS += tst_atomic4.c
SRCS += tst_atomic5.c

SRCS += tst_spinlock0.c
SRCS += tst_spinlock1.c
SRCS += tst_spinlock2.c
SRCS += tst_spinlock2_5w.c
SRCS += tst_spinlock2_15w.c
SRCS += tst_spinlock2_31w.c
SRCS += tst_spinlock3_7w.c
SRCS += tst_spinlock3_uc7w.c
SRCS += tst_spinlock3_uc7w2.c
SRCS += tst_spinlock3_uc7w3.c
SRCS += tst_rwlock0.c
SRCS += tst_rwlock1.c

SRCS += tst_cache0.c
SRCS += tst_cache1.c
SRCS += tst_cache2.c
SRCS += tst_cache3.c
SRCS += tst_cache4.c
SRCS += tst_cache4l.c
SRCS += tst_cache4s.c

SRCS += tst_mem0.c

SRCS += tst_mixed.c
SRCS += tst_chain0.c
SRCS += tst_consume.c

SRCS += tst_exception.c
#SRCS += tst_float.c
#SRCS += tst_float1.c
SRCS += tst_dma0.c
#SRCS += tst_dma1.c
SRCS += tst_uca.c
SRCS += tst_uca1.c
SRCS += tst_uca_wrb.c

