
# This order is important
obj-y += tst_smp_ipi.o
obj-y += tst_pcpu.o
obj-y += tst_smp_msg0.o
obj-y += tst_smp_msg1.o

obj-y += tst_llsc.o
obj-y += tst_atomic0.o
obj-y += tst_atomic1.o
obj-y += tst_atomic2.o
obj-y += tst_atomic3.o
obj-y += tst_atomic4.o
obj-y += tst_atomic5.o

obj-y += tst_spinlock0.o
obj-y += tst_spinlock1.o
obj-y += tst_spinlock2.o
obj-y += tst_spinlock2_5w.o
obj-y += tst_spinlock2_15w.o
obj-y += tst_spinlock2_31w.o
obj-y += tst_spinlock3_7w.o
obj-y += tst_spinlock3_uc7w.o
obj-y += tst_spinlock3_uc7w2.o
obj-y += tst_spinlock3_uc7w3.o
obj-y += tst_rwlock0.o
obj-y += tst_rwlock1.o

obj-y += tst_cache0.o
obj-y += tst_cache1.o
obj-y += tst_cache2.o
obj-y += tst_cache3.o
obj-y += tst_cache4.o
obj-y += tst_cache4l.o
#obj-y += tst_cache4s.o

obj-y += tst_mem0.o

obj-y += tst_mixed.o
#obj-y += tst_chain0.o
#obj-y += tst_consume.o
