

#obj-y += tst_exception.o
#obj-y += tst_float.o
#obj-y += tst_float1.o
#obj-y += tst_dma0.o
#obj-y += tst_dma1.o
obj-y += tst_uca.o
obj-y += tst_uca1.o
#obj-y += tst_uca_wrb.o
#obj-y += tst_ddr.o
obj-y += tst_buddy.o
