

obj-y	= start.o exp_int.o tlb_miss.o trap.o mmu.o irq.o
obj-y   += base.o param.o cache.o pcpu.o smp.o
obj-y   += smp_msg.o smp_fun.o smp_stat.o smp_puts.o
obj-y   += pmon.o sys.o cmain.o init.o
obj-y	+= mem.o

obj-$(CONFIG_NCSIM) += rom.o
